-- MySQL Script generated by MySQL Workbench
-- Sun Dec 16 17:37:44 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema spcb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spcb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spcb` DEFAULT CHARACTER SET utf8 ;
USE `spcb` ;

-- -----------------------------------------------------
-- Table `spcb`.`TipoSetor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spcb`.`TipoSetor` (
  `idTipoSetor` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `observacao` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoSetor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spcb`.`Setor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spcb`.`Setor` (
  `idsetor` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `tel1` VARCHAR(45) NULL,
  `tel2` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `logradouro` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `latitude` VARCHAR(45) NULL,
  `longitude` VARCHAR(45) NULL,
  `gestor` VARCHAR(255) NULL,
  `TipoSetor_idTipoSetor` INT NOT NULL,
  PRIMARY KEY (`idsetor`),
  INDEX `fk_Setor_TipoSetor1_idx` (`TipoSetor_idTipoSetor` ASC) VISIBLE,
  CONSTRAINT `fk_Setor_TipoSetor1`
    FOREIGN KEY (`TipoSetor_idTipoSetor`)
    REFERENCES `spcb`.`TipoSetor` (`idTipoSetor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `spcb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spcb`.`Usuario` (
  `idusuario` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  `Setor_idsetor` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_Usuario_Setor1_idx` (`Setor_idsetor` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Setor1`
    FOREIGN KEY (`Setor_idsetor`)
    REFERENCES `spcb`.`Setor` (`idsetor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spcb`.`PrestadoraServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spcb`.`PrestadoraServico` (
  `idPrestadoraServico` INT NOT NULL,
  `raza_social` VARCHAR(255) NULL,
  `cnpj` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  PRIMARY KEY (`idPrestadoraServico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spcb`.`Ocorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spcb`.`Ocorrencia` (
  `idOcorrencia` INT NOT NULL,
  `numero` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  PRIMARY KEY (`idOcorrencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spcb`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spcb`.`Cargo` (
  `idCargo` INT NOT NULL,
  `nome` VARCHAR(255) NULL,
  `descricao` VARCHAR(255) NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spcb`.`Colaborador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spcb`.`Colaborador` (
  `idColaborador` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(255) NULL,
  `data_admissao` DATETIME NULL,
  `telefone` VARCHAR(255) NULL,
  `PrestadoraServico_idPrestadoraServico` INT NOT NULL,
  `Ocorrencia_idOcorrencia` INT NOT NULL,
  `Cargo_idCargo` INT NOT NULL,
  `Setor_idsetor` INT NOT NULL,
  PRIMARY KEY (`idColaborador`),
  INDEX `fk_Colaborador_PrestadoraServico1_idx` (`PrestadoraServico_idPrestadoraServico` ASC) VISIBLE,
  INDEX `fk_Colaborador_Ocorrencia1_idx` (`Ocorrencia_idOcorrencia` ASC) VISIBLE,
  INDEX `fk_Colaborador_Cargo1_idx` (`Cargo_idCargo` ASC) VISIBLE,
  INDEX `fk_Colaborador_Setor1_idx` (`Setor_idsetor` ASC) VISIBLE,
  CONSTRAINT `fk_Colaborador_PrestadoraServico1`
    FOREIGN KEY (`PrestadoraServico_idPrestadoraServico`)
    REFERENCES `spcb`.`PrestadoraServico` (`idPrestadoraServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colaborador_Ocorrencia1`
    FOREIGN KEY (`Ocorrencia_idOcorrencia`)
    REFERENCES `spcb`.`Ocorrencia` (`idOcorrencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colaborador_Cargo1`
    FOREIGN KEY (`Cargo_idCargo`)
    REFERENCES `spcb`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colaborador_Setor1`
    FOREIGN KEY (`Setor_idsetor`)
    REFERENCES `spcb`.`Setor` (`idsetor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spcb`.`Historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spcb`.`Historico` (
  `idHistorico` INT NOT NULL,
  `data` DATETIME NOT NULL,
  `observacao` VARCHAR(255) NULL,
  `Colaborador_idColaborador` INT NOT NULL,
  `Setor_idsetor` INT NOT NULL,
  PRIMARY KEY (`idHistorico`),
  INDEX `fk_Historico_Colaborador_idx` (`Colaborador_idColaborador` ASC) VISIBLE,
  INDEX `fk_Historico_Setor1_idx` (`Setor_idsetor` ASC) VISIBLE,
  CONSTRAINT `fk_Historico_Colaborador`
    FOREIGN KEY (`Colaborador_idColaborador`)
    REFERENCES `spcb`.`Colaborador` (`idColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Historico_Setor1`
    FOREIGN KEY (`Setor_idsetor`)
    REFERENCES `spcb`.`Setor` (`idsetor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
